config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'pages#splash'

  resources :categories do
    resources :subcategories
  end

  resources :listings do
    collection do
      get 'search'
    end
  end

  get 'splash',   to: 'pages#splash',  as: :mock_splash
  get 'home',     to: 'pages#home',    as: :mock_home

  get 'about',    to: 'pages#about'
  get 'terms',    to: 'pages#terms'
  get 'privacy',  to: 'pages#privacy'
  get 'contact',  to: 'pages#contact'

  match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories
  has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :categories
  belongs_to :subcategories

  geocoded_by :address_for_geocode
  after_validation :geocode

  def address_for_geocode
    [city, state, zipcode, country].join(', ')
  end

  def self.search(params)
    listings = Listing.where(category_id: params[:category].to_i)
    listings = listings.where('title like ? or description like ?', params[:search], params[:search]) if params[:search].present?
    listings = listings.near(params[:location], 20) if params[:location].present?
    listings
  end
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  def send_devise_notification(notification, *args)
    if Rails.env.production?
      # No worker process in production to handle scheduled tasks
      devise_mailer.send(notification, self, *args).deliver_now
    else
      devise_mailer.send(notification, self, *args).deliver_later
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :detect_device_variant
  before_action :configure_permitted_parameters, if: :devise_controller?





  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    # devise_parameter_sanitizer.for(:sign_in) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end

  private

  def detect_device_variant
    request.variant = :tablet if browser.tablet?
    request.variant = :desktop if !browser.mobile? && !browser.tablet?
  end

  def set_layout
    case action_name
    when "splash"
      "splash"
    end

    # NOTE ccm:  I want to be able to switch between layouts using variants.
    # Why do these not work?

    # if browser.tablet?
    #   "application"
    # elsif !browser.mobile? && !browser.tablet?
    #   "splash"
    # else
    #   "application"
    # end

    # case request.variant
    # when browser.tablet?
    #   "application"
    # when !browser.mobile? && !browser.tablet?
    #   "splash"
    # else
    #   "application"
    # end

    # if request.variant.tablet?
    #   "application"
    # elsif request.variant.desktop?
    #   "splash"
    # else
    #   "application"
    # end

    # if request.variant.include? :tablet
    #   "application"
    # elsif request.variant.include? :desktop
    #   "splash"
    # else
    #   "splash"
    # end

    # if params[:variant] == 'tablet'
    #   "application"
    # elsif params[:variant] == 'desktop'
    #   "splash"
    # else
    #   "splash"
    # end

    # case request.variant
    # when :tablet
    #   "tablet"
    # when :desktop
    #   "splash"
    # else
    #   "splash"
    # end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # FIXME ccm: Change from hard coding category.
  def index
    # @categories             = Category.all
    # FIXME ccm: Add .order('') here, out of view.
    # This is not doing the trick:
    # @categories             = Category.select('id, name').order('id ASC')
    @categories             = Category.select('id, name')
    @automotive_services    = @categories[0]
    @beauty                 = @categories[1]
    @business               = @categories[2]
    @dating                 = @categories[3]
    @dining                 = @categories[4]
    @education_and_training = @categories[5]
    @farming_livestock      = @categories[6]
    @for_sale               = @categories[7]
    @healthcare             = @categories[8]
    @home                   = @categories[9]
    @top_industries         = @categories[10]
    @jobs                   = @categories[11]
    @local_services         = @categories[12]
    @meet_up                = @categories[13]
    @new_cars               = @categories[14]
    @part_time_jobs         = @categories[15]
    @pets_pet_products      = @categories[16]
    @real_estate            = @categories[17]
    @recreation             = @categories[18]
    @resumes                = @categories[19]
    @ticketing              = @categories[20]
    @tourism                = @categories[21]
    @used_cars              = @categories[22]
  end

  def show
    @listings = Listing.where(category_id: params[:id])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.save
    redirect_to @listing
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def search
    @listings = Listing.search(params)
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :description, :city, :state, :zipcode, :country, :category_id, :subcategory_id )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout :set_layout

  def splash
    render "pages/mock/splash"
  end

  def home
    render "pages/mock/home"
  end

  def about
  end

  def terms
  end

  def privacy
  end

  def contact
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def show
    @listings = Listing.where(subcategory_id: params[:id])
  end

  def find_by_category
    category = Category.find(params[:category_id])
    subcategories = category.subcategories.find_all
    render json: { subcategories: subcategories }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.haml
- content_for :title do
  Home
= nav_at 'Home', in: 'tabs_main'

.listings
  -# FIXME ccm: Need to be able to change order of subcategories.
  .col1
    -# FIXME ccm: City needs to be dynamically generated.
    -# FIXME ccm: Refactor into helper.
    -# FIXME ccm: The very last record does not need a %br
    %h2= link_to 'Miami ' + @real_estate.name, category_path(@real_estate)
    -# NOTE ccm: Had to provide order, array reversed in Heroku. Weird?
    -# Try to move into controller, but did not work.
    - @real_estate.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@real_estate, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@real_estate, subcategory)
    .line

    -# FIXME ccm: Needs...
    -# %h5 By Brand
    -# %h5 Manufacturer Certified Pre-Owned
    %h3
      = link_to @used_cars.name, category_path(@used_cars)
      %span= link_to 'nationwide'
      %span= link_to 'local dealers'
    - @used_cars.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@used_cars, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@used_cars, subcategory)
    .line

    %h3
      = link_to @new_cars.name, category_path(@new_cars)
      %span= link_to 'new ford fusion', mock_home_path, class: 'red'
    - @new_cars.subcategories.order('id ASC').each_with_index do |subcategory, index|
      - if index.even?
        %em.c2= link_to subcategory.name, category_subcategory_path(@new_cars, subcategory)
      - if index.odd?
        = link_to subcategory.name, category_subcategory_path(@new_cars, subcategory)
        %br
    .line
    -# FIXME ccm: Needs %h5 Maintenance
    %h3= link_to @automotive_services.name, category_path(@automotive_services)
    - @automotive_services.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@automotive_services, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@automotive_services, subcategory)
    .line

    %h3= link_to @education_and_training.name, category_path(@education_and_training)
    - @education_and_training.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@education_and_training, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@education_and_training, subcategory)

  .col2
    %h2
      = link_to @for_sale.name, category_path(@for_sale)
      %span= link_to 'local garage sales', mock_home_path, class: 'red'
    -# FIXME ccm: Needs...
    -# %h5 Digital • Mobile • Electronic
    -# %h5 Furniture • Appliances
    -# %h5 Department Store • General
    -# %h5 Office Equipment
    -# FIXME ccm: Will also need to be able to apply classes to specific items.
    - @for_sale.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@for_sale, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@for_sale, subcategory)
    .line

    %h3= link_to @pets_pet_products.name, category_path(@pets_pet_products)
    - @pets_pet_products.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@pets_pet_products, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@pets_pet_products, subcategory)
    .line

    %h3= link_to @ticketing.name, category_path(@ticketing)
    - @ticketing.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@ticketing, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@ticketing, subcategory)

  .col3
    %h2
      = link_to @jobs.name, category_path(@jobs)
      %span= link_to 'create online resume', mock_home_path

    -# - @jobs.subcategories.each_slice(4) do |array|
    -#   - array.order('id ASC').each_with_index do |subcategory, i|
    -#     -# The problem here will be that index starts with 0.
    -#     - if i % 4 != 0
    -#       %em.c4= link_to subcategory.name, category_subcategory_path(@jobs, subcategory)
    -#     - if i % 4 == 0
    -#       = link_to subcategory.name, category_subcategory_path(@jobs, subcategory)
    -#       %br

    -# - @jobs.subcategories.each_slice(4) do |*first_subcategories, last_subcategory|
    -#   - first_subcategories.each do |subcategory|
    -#     %em.c4= link_to subcategory.name, category_subcategory_path(@jobs, subcategory)
    -#   = link_to last_subcategory.name, category_subcategory_path(@jobs, last_subcategory)
    -#   %br

    - @jobs.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 4 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@jobs, subcategory)
        %br
      - else
        %em.c4= link_to subcategory.name, category_subcategory_path(@jobs, subcategory)
    .line

    %h3= link_to @top_industries.name, category_path(@top_industries)

    -# - @top_industries.subcategories.order('id ASC').each_with_index do |subcategory, i|
    -#   - second_column = (i+1) % 2 == 0
    -#   - third_column = (i+1) % 3 == 0
    -#   - if third_column
    -#     = link_to subcategory.name, category_subcategory_path(@top_industries, subcategory)
    -#     %br
    -#   - elsif second_column
    -#     %em.c3b= link_to subcategory.name, category_subcategory_path(@top_industries, subcategory)
    -#   - else
    -#     %em.c3a= link_to subcategory.name, category_subcategory_path(@top_industries, subcategory)

    - @top_industries.subcategories.order('id ASC').each_slice(3) do |s1, s2, s3|
      - unless s1.nil?
        %em.c3a= link_to s1.name, category_subcategory_path(@top_industries, s1)
      - unless s2.nil?
        %em.c3b= link_to s2.name, category_subcategory_path(@top_industries, s2)
      - unless s3.nil?
        = link_to s3.name, category_subcategory_path(@top_industries, s3)
        %br
    .line

    %h3= link_to @part_time_jobs.name, category_path(@part_time_jobs)
    - @part_time_jobs.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 4 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@part_time_jobs, subcategory)
        %br
      - else
        %em.c4= link_to subcategory.name, category_subcategory_path(@part_time_jobs, subcategory)
    .line

    %h3
      = link_to @resumes.name, category_path(@resumes)
      %span= link_to 'resume search', mock_home_path
    - @resumes.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 3 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@resumes, subcategory)
        %br
      - else
        %em.c3= link_to subcategory.name, category_subcategory_path(@resumes, subcategory)
    .line

    %h3
      = link_to @meet_up.name, category_path(@meet_up)
      %span= link_to 'start a group', mock_home_path
    - @meet_up.subcategories.order('id ASC').each_slice(3) do |s1, s2, s3|
      - unless s1.nil?
        %em.c3a= link_to s1.name, category_subcategory_path(@meet_up, s1)
      - unless s2.nil?
        %em.c3b= link_to s2.name, category_subcategory_path(@meet_up, s2)
      - unless s3.nil?
        = link_to s3.name, category_subcategory_path(@meet_up, s3)
        %br
    .line

    %h3= link_to 'Miami ' + @dating.name, category_path(@dating)
    - @dating.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@dating, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@dating, subcategory)

  .col4
    %h2= link_to @local_services.name, category_path(@local_services)
    .line

    %h3= link_to @home.name, category_path(@home)
    - @home.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 3 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@home, subcategory)
        %br
      - else
        %em.c3= link_to subcategory.name, category_subcategory_path(@home, subcategory)
    .line

    %h3= link_to @tourism.name, category_path(@tourism)
    - @tourism.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 3 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@tourism, subcategory)
        %br
      - else
        %em.c3= link_to subcategory.name, category_subcategory_path(@tourism, subcategory)

    .line

    %h3= link_to @business.name, category_path(@business)
    - @business.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@business, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@business, subcategory)
    .line

    %h3= link_to @recreation.name, category_path(@recreation)
    - @recreation.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@recreation, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@recreation, subcategory)
    .line

    %h3= link_to @healthcare.name, category_path(@healthcare)
    - @healthcare.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 3 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@healthcare, subcategory)
        %br
      - else
        %em.c3= link_to subcategory.name, category_subcategory_path(@healthcare, subcategory)
    .line

    %h3= link_to @dining.name, category_path(@dining)
    - @dining.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 3 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@dining, subcategory)
        %br
      - else
        %em.c3= link_to subcategory.name, category_subcategory_path(@dining, subcategory)
    .line

    %h3= link_to @farming_livestock.name, category_path(@farming_livestock)
    - @farming_livestock.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 2 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@farming_livestock, subcategory)
        %br
      - else
        %em.c2= link_to subcategory.name, category_subcategory_path(@farming_livestock, subcategory)
    .line

    %h3= link_to @beauty.name, category_path(@beauty)
    - @beauty.subcategories.order('id ASC').each_with_index do |subcategory, i|
      - section_break = (i+1) % 4 == 0
      - if section_break
        = link_to subcategory.name, category_subcategory_path(@beauty, subcategory)
        %br
      - else
        %em.c4= link_to subcategory.name, category_subcategory_path(@beauty, subcategory)

app/views/categories/show.html.haml
-# FIXME ccm: This is going to be a problem.
-# Title and Tabs should not be hardcoded here.
- content_for :title do
  Housing
= nav_at 'Housing', in: 'tabs_main'

- if @listings.present?
  %ul
  - @listings.each do |listing|
    %li
      = listing.id
      = listing.created_at.strftime('%B %d, %Y')
      = link_to listing.title, listing
      = listing.description
      = listing.city
      = listing.state
      = listing.zipcode
      = listing.country
- else
  %p Be the first to post!
  = link_to 'Post', new_listing_path, class: 'button btn-blue'

app/views/layouts/desktop/_banner_ad.html.haml
#banner-ad
  %img{:src => 'http://placehold.it/1190x50', :alt => 'Advertisement', :width => '1190', :height => '50'}

app/views/layouts/desktop/_banner_main.html.haml
#banner
  .logo
    = link_to image_tag('logos/130x60.gif', alt: 'Ojala logo', width: '130', height: '60'), root_path, title: 'Link to Ojala Homepage'

  .micro-ad
    %img{:src => 'http://placehold.it/150x50', :alt => 'Advertisement', :width => '150', :height => '50'}

  .search
    = render 'layouts/desktop/banner_search'
    %ul.search-nav
      %li= link_to 'Buy Tickets', mock_home_path
      %li= link_to 'Horoscope', mock_home_path
      %li= link_to 'City Dating', mock_home_path
      %li= link_to 'Relevant', mock_home_path
      %li= link_to 'Pertinent', mock_home_path
      %li= link_to 'Current', mock_home_path
  .post
    = link_to 'Post FREE Ads', new_listing_path, class: 'button btn-blue'
    = link_to 'Modify/Delete', mock_home_path

app/views/layouts/desktop/_banner_search.html.haml
= form_tag search_listings_path, method: :get do
  / .search-input
  = text_field_tag :search, nil, placeholder: 'I\'m looking for...'
  / .search-near
  = text_field_tag :location, nil, placeholder: 'Near'
  / .search-categor
  = select_tag :category, options_for_select(Category.all.map { |c| [c.name,  c.id] })
  / .search-button
  = submit_tag 'Search'

app/views/layouts/desktop/_top_bar.html.haml
#top-bar.clearfix
  .location
    United States
    [
    = link_to 'Change', mock_home_path
    ]

  %ul.menubar
    - if user_signed_in?
      %li.menubar-item= link_to current_user.username, edit_user_registration_path, class: 'menubar-item-target'
      %li.menubar-item= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'menubar-item-target'
    - else
      %li.menubar-item= link_to 'Login', new_user_session_path, class: 'menubar-item-target'
      %li.menubar-item= link_to 'Sign Up', new_user_registration_path, class: 'menubar-item-target'
    %li.menubar-item
      = link_to 'My Ojala', mock_home_path, class: 'menubar-item-target'
      %i.caret-icon
      %ul.menu
        %li.menu-item= link_to 'Profile', edit_user_registration_path, class: 'menubar-item-target'
        %li.menu-item= link_to 'My Publishers', mock_home_path, class: 'menu-item-target'
        %li.menu-item= link_to 'Recruitment / CV', mock_home_path, class: 'menu-item-target'
        %li.menu-item= link_to 'Buyers', mock_home_path, class: 'menu-item-target'
        %li.menu-item= link_to 'Individual sellers', mock_home_path, class: 'menu-item-target'
        %li.menu-item= link_to 'Customer Service', mock_home_path, class: 'menu-item-target'
    %li.menubar-item= link_to 'VIP center', mock_home_path, class: 'menubar-item-target'
    %li.menubar-item= link_to 'Help', mock_home_path, class: 'menubar-item-target'
    %li.menubar-item
      = link_to 'History', mock_home_path, class: 'menubar-item-target'
      %ul.menu
        %li.menu-item
          .menu-item-target No browsing history ...
    -# %li.menubar-item= link_to 'Navigation', mock_home_path, class: 'menubar-item-target'
    %li.menubar-item
      .menubar-item-target
        .box-shadow-menu
      %ul.menu
        %li.menu-item= link_to 'Something', mock_home_path, class: 'menu-item-target'
        %li.menu-item= link_to 'Something', mock_home_path, class: 'menu-item-target'
        %li.menu-item= link_to 'Something', mock_home_path, class: 'menu-item-target'
        %li.menu-item= link_to 'Something', mock_home_path, class: 'menu-item-target'
        %li.menu-item= link_to 'Something', mock_home_path, class: 'menu-item-target'

app/views/layouts/phone/_footer.html.haml
%footer{role: 'contentinfo'}
  .container
    %ul
      %li
        = link_to 'About', about_path, title: ''
      %li
        = link_to 'Terms of Use', terms_path, title: ''
      %li
        = link_to 'Privacy', privacy_path, title: ''
      %li
        = link_to 'Contact', contact_path, title: ''
    %p.copyright &copy; XXX 2015

app/views/pages/mock/_business.html.haml
%h3= link_to 'Business', mock_home_path

%em.c2= link_to 'patent trademark', mock_home_path
= link_to 'financial accounting', mock_home_path
%br
%em.c2= link_to 'taxes', mock_home_path
= link_to 'legal', mock_home_path
%br
%em.c2= link_to 'consulting', mock_home_path
= link_to 'freight logistics', mock_home_path
%br
%em.c2= link_to 'courier insurance', mock_home_path
= link_to 'freight trains', mock_home_path
%br
%em.c2= link_to 'site construction', mock_home_path
= link_to 'network cabling', mock_home_path
%br
%em.c2= link_to 'advertising media', mock_home_path
= link_to 'design planning', mock_home_path
%br
%em.c2= link_to 'packaging', mock_home_path
= link_to 'printing', mock_home_path
%br
%em.c2= link_to 'customized gifts', mock_home_path
= link_to 'exhibition services', mock_home_path
%br
%em.c2= link_to 'translation', mock_home_path
= link_to 'lease', mock_home_path
%br
%em.c2= link_to 'equipment maint', mock_home_path
= link_to 'building', mock_home_path
%br
%em.c2= link_to 'mechanical maint', mock_home_path
= link_to 'business registration', mock_home_path

app/views/pages/mock/_education_training.html.haml
%h3= link_to 'Education and Training', mock_home_path

%em.c2= link_to 'tutoring agency', mock_home_path
= link_to 'private tutor', mock_home_path
%br
%em.c2= link_to 'language', mock_home_path
= link_to 'arts', mock_home_path
%br
%em.c2= link_to 'vocational', mock_home_path
= link_to 'sports', mock_home_path
%br
%em.c2= link_to 'design', mock_home_path
= link_to 'computer', mock_home_path
%br
%em.c2= link_to 'classes', mock_home_path
= link_to 'abroad', mock_home_path
%br
= link_to 'academic institutions', mock_home_path

app/views/pages/mock/_healthcare.html.haml
%h3= link_to 'Healthcare', mock_home_path

%em.c3= link_to 'dermatology', mock_home_path
%em.c3= link_to 'gynecology', mock_home_path
= link_to 'genital warts', mock_home_path
%br
%em.c3= link_to 'genital herpes', mock_home_path
%em.c3= link_to 'cosmetic', mock_home_path
= link_to 'impotence', mock_home_path
%br
%em.c3= link_to 'infertility', mock_home_path
%em.c3= link_to 'massage', mock_home_path
= link_to 'premature ejac', mock_home_path

app/views/pages/mock/_industries.html.haml
%h3= link_to 'Top Industries', mock_home_path

%em.c3a= link_to 'medical / care', mock_home_path
%em.c3b= link_to 'massage', mock_home_path
= link_to 'computer / network', mock_home_path
%br
%em.c3a= link_to 'market / media', mock_home_path
%em.c3b= link_to 'catering', mock_home_path
= link_to 'pharma / biotech', mock_home_path
%br
%em.c3a= link_to 'electrical', mock_home_path
%em.c3b= link_to 'electronic', mock_home_path
= link_to 'advert / exhibit', mock_home_path
%br
%em.c3a= link_to 'depart store', mock_home_path
%em.c3b= link_to 'supermarket', mock_home_path
= link_to 'hospitality / tourism', mock_home_path
%br
%em.c3a= link_to 'warehouse', mock_home_path
%em.c3b= link_to 'logistics', mock_home_path
= link_to 'finance / banking', mock_home_path
%br
%em.c3a= link_to 'sports / fitness', mock_home_path
%em.c3b= link_to 'building', mock_home_path
= link_to 'equip / machinery', mock_home_path
%br
%em.c3a= link_to 'beauty / hair', mock_home_path
%em.c3b= link_to 'art / design', mock_home_path
= link_to 'entertain / leisure', mock_home_path
%br
%em.c3a= link_to 'edu / training', mock_home_path
%em.c3b= link_to 'textile / food', mock_home_path
= link_to 'automotive services', mock_home_path

app/views/pages/mock/_part_time.html.haml
%h3= link_to 'Part-time Jobs', mock_home_path

%em.c4= link_to 'students', mock_home_path
%em.c4= link_to 'staff', mock_home_path
%em.c4= link_to 'leaflet dist', mock_home_path
= link_to 'tutoring', mock_home_path
%br
%em.c4= link_to 'translations', mock_home_path
%em.c4= link_to 'graphic des', mock_home_path
%em.c4= link_to 'promotional', mock_home_path
= link_to 'accounting', mock_home_path
%br
%em.c4= link_to 'web design', mock_home_path
%em.c4= link_to 'survey', mock_home_path
%em.c4= link_to 'driver', mock_home_path
= link_to 'more »', mock_home_path